/*    File: QuotePanel.java
 *    Name: John West
 *    Revised: 6/18/2013
 *    Course: CS150 - Introduction to Computing II - Summer 13
 * 
 *    Desc: This program ...Uses GUI and Java Class implementation.
 */
package hw02;

/**
 *
 * @author Johnny
 */
public class QuotePanel extends javax.swing.JPanel {

    private StringFormat text;
    String line;

    public QuotePanel() {
        initComponents();
        line = "Great minds discuss ideas; average minds discuss events; small minds discuss people.";
        text = new StringFormat(line);
        originalTextField.setText(text.getText());
        upperCaseTextField.setText(text.toUpperCase());
        lowerCaseTextField.setText(text.toLowerCase());
        lowerCaseTextField.setText(text.toLowerCase());
        capitalizedTextField.setText(text.wordCapitalize());
        wordCountTextField.setText(Integer.toString(text.wordCount()));
        alphabeticCharCountTextField.setText(Integer.toString(text.alphabeticCharCount()));
        spaceCharCountTextField.setText(Integer.toString(text.spaceCharCount()));
        spaceCharCountTextField.setText(Integer.toString(text.spaceCharCount()));
        punctuationCharCountTextField.setText(Integer.toString(text.punctuationCharCount()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        originalLabel = new javax.swing.JLabel();
        originalPanel = new javax.swing.JPanel();
        originalTextField = new javax.swing.JTextField();
        upperCaseLabel = new javax.swing.JLabel();
        upperCasePanel = new javax.swing.JPanel();
        upperCaseTextField = new javax.swing.JTextField();
        lowerCaseLabel = new javax.swing.JLabel();
        lowerCasePanel = new javax.swing.JPanel();
        lowerCaseTextField = new javax.swing.JTextField();
        capitalizedLabel = new javax.swing.JLabel();
        captializedPanel = new javax.swing.JPanel();
        capitalizedTextField = new javax.swing.JTextField();
        countLabel = new javax.swing.JLabel();
        countPanel = new javax.swing.JPanel();
        wordCountLabel = new javax.swing.JLabel();
        wordCountTextField = new javax.swing.JTextField();
        alphabeticCharCountLabel = new javax.swing.JLabel();
        alphabeticCharCountTextField = new javax.swing.JTextField();
        spaceCharCountLabel = new javax.swing.JLabel();
        spaceCharCountTextField = new javax.swing.JTextField();
        punctuationCharCountLabel = new javax.swing.JLabel();
        punctuationCharCountTextField = new javax.swing.JTextField();

        originalLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        originalLabel.setText("Original");

        originalPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        originalTextField.setEditable(false);
        originalTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        originalTextField.setFocusable(false);
        originalTextField.setKeymap(null);

        javax.swing.GroupLayout originalPanelLayout = new javax.swing.GroupLayout(originalPanel);
        originalPanel.setLayout(originalPanelLayout);
        originalPanelLayout.setHorizontalGroup(
            originalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(originalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(originalTextField)
                .addContainerGap())
        );
        originalPanelLayout.setVerticalGroup(
            originalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(originalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(originalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        upperCaseLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        upperCaseLabel.setText("Upper Case");

        upperCasePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        upperCaseTextField.setEditable(false);
        upperCaseTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        upperCaseTextField.setFocusable(false);

        javax.swing.GroupLayout upperCasePanelLayout = new javax.swing.GroupLayout(upperCasePanel);
        upperCasePanel.setLayout(upperCasePanelLayout);
        upperCasePanelLayout.setHorizontalGroup(
            upperCasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperCasePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(upperCaseTextField)
                .addContainerGap())
        );
        upperCasePanelLayout.setVerticalGroup(
            upperCasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperCasePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(upperCaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lowerCaseLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lowerCaseLabel.setText("Lower Case");

        lowerCasePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        lowerCaseTextField.setEditable(false);
        lowerCaseTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lowerCaseTextField.setFocusable(false);

        javax.swing.GroupLayout lowerCasePanelLayout = new javax.swing.GroupLayout(lowerCasePanel);
        lowerCasePanel.setLayout(lowerCasePanelLayout);
        lowerCasePanelLayout.setHorizontalGroup(
            lowerCasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lowerCasePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lowerCaseTextField)
                .addContainerGap())
        );
        lowerCasePanelLayout.setVerticalGroup(
            lowerCasePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lowerCasePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lowerCaseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        capitalizedLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        capitalizedLabel.setText("Capitalized");

        captializedPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        capitalizedTextField.setEditable(false);
        capitalizedTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        capitalizedTextField.setFocusable(false);

        javax.swing.GroupLayout captializedPanelLayout = new javax.swing.GroupLayout(captializedPanel);
        captializedPanel.setLayout(captializedPanelLayout);
        captializedPanelLayout.setHorizontalGroup(
            captializedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(captializedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(capitalizedTextField)
                .addContainerGap())
        );
        captializedPanelLayout.setVerticalGroup(
            captializedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(captializedPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(capitalizedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        countLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        countLabel.setText("Count");

        countPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        wordCountLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        wordCountLabel.setText("Word:");

        wordCountTextField.setEditable(false);
        wordCountTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        wordCountTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        wordCountTextField.setFocusable(false);

        alphabeticCharCountLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        alphabeticCharCountLabel.setText("Alphabetic:");

        alphabeticCharCountTextField.setEditable(false);
        alphabeticCharCountTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        alphabeticCharCountTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        alphabeticCharCountTextField.setFocusable(false);

        spaceCharCountLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spaceCharCountLabel.setText("Space:");

        spaceCharCountTextField.setEditable(false);
        spaceCharCountTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        spaceCharCountTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        spaceCharCountTextField.setFocusable(false);

        punctuationCharCountLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        punctuationCharCountLabel.setText("Punctuation:");

        punctuationCharCountTextField.setEditable(false);
        punctuationCharCountTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        punctuationCharCountTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        punctuationCharCountTextField.setFocusable(false);

        javax.swing.GroupLayout countPanelLayout = new javax.swing.GroupLayout(countPanel);
        countPanel.setLayout(countPanelLayout);
        countPanelLayout.setHorizontalGroup(
            countPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(countPanelLayout.createSequentialGroup()
                .addContainerGap(593, Short.MAX_VALUE)
                .addGroup(countPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(countPanelLayout.createSequentialGroup()
                        .addComponent(wordCountLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(wordCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(countPanelLayout.createSequentialGroup()
                        .addComponent(punctuationCharCountLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(punctuationCharCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(countPanelLayout.createSequentialGroup()
                        .addComponent(alphabeticCharCountLabel)
                        .addGap(10, 10, 10)
                        .addComponent(alphabeticCharCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(countPanelLayout.createSequentialGroup()
                        .addComponent(spaceCharCountLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spaceCharCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        countPanelLayout.setVerticalGroup(
            countPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(countPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(countPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wordCountLabel)
                    .addComponent(wordCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(countPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alphabeticCharCountLabel)
                    .addComponent(alphabeticCharCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(countPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spaceCharCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spaceCharCountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(countPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(punctuationCharCountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(punctuationCharCountLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(originalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(upperCasePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lowerCasePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(captializedPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(originalLabel)
                            .addComponent(upperCaseLabel)
                            .addComponent(lowerCaseLabel)
                            .addComponent(capitalizedLabel)
                            .addComponent(countLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(countPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(originalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(originalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(upperCaseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(upperCasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lowerCaseLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lowerCasePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(capitalizedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(captializedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(countLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(countPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alphabeticCharCountLabel;
    private javax.swing.JTextField alphabeticCharCountTextField;
    private javax.swing.JLabel capitalizedLabel;
    private javax.swing.JTextField capitalizedTextField;
    private javax.swing.JPanel captializedPanel;
    private javax.swing.JLabel countLabel;
    private javax.swing.JPanel countPanel;
    private javax.swing.JLabel lowerCaseLabel;
    private javax.swing.JPanel lowerCasePanel;
    private javax.swing.JTextField lowerCaseTextField;
    private javax.swing.JLabel originalLabel;
    private javax.swing.JPanel originalPanel;
    private javax.swing.JTextField originalTextField;
    private javax.swing.JLabel punctuationCharCountLabel;
    private javax.swing.JTextField punctuationCharCountTextField;
    private javax.swing.JLabel spaceCharCountLabel;
    private javax.swing.JTextField spaceCharCountTextField;
    private javax.swing.JLabel upperCaseLabel;
    private javax.swing.JPanel upperCasePanel;
    private javax.swing.JTextField upperCaseTextField;
    private javax.swing.JLabel wordCountLabel;
    private javax.swing.JTextField wordCountTextField;
    // End of variables declaration//GEN-END:variables
}
